function plotStrExpFit( x, y, a1, a2, beta, tau, chiSquared, fittedTotal, n, numChunks, numStrExpChunks, numFuncs)
%==========================================================================
% This function plots a pretty final plot given the initial
% data, coefficients, and fitted data.
%
% Created by: Laura Nichols
% Creation date: 19 February 2017
% Contact: lnichols11@my.apsu.edu
%==========================================================================

% If the user cut the linear portion then only give
% table for stretched exponential bits

fitted = fittedTotal{1,1};

for i = 2:numChunks
    fitted = [fitted; fittedTotal{1,i}];
end

%--------------------------------------------------------------------------
% Plot the fitted curved along with data
f = figure( n );
cla reset
h = plot(x, y, fitted(:,1), fitted(:,2));
% Make the fitted line thicker
set(h(2),'linewidth',2)
% Set font size
ax = gca;
ax.FontSize = 16;         
% Create a legend
legend( h, 'Experimental Data', 'Stretched Exponential Fit', 'Location', 'NorthEast' );
% Label axes
xlabel('Time (s)')
ylabel('Transmittance (%)')

if nargin == 12
    %--------------------------------------------------------------------------
    % Add data to table  and format based on how many stretched 
    % exponential chunks you have
    if numStrExpChunks == 1
        % Data for table
        dat =  {'        a1', a1(1);...
                '        a2', a2(1);...   
                '        beta', beta(1);...
                '        tau', tau(1); ...
                '        numFuncs', numFuncs(1); ...
                '        chi^2', chiSquared(1)};
        columnname =   {'Parameter', 'Decay 1'};
        columnformat = {'char', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.688 0.504 0.192 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 2
        % Data for table
        dat =  {'        a1', a1(1), a1(2);...
                '        a2', a2(1), a2(2);...   
                '        beta', beta(1), beta(2);...
                '        tau', tau(1), tau(2); ...
                '        numFuncs', numFuncs(1), numFuncs(2); ...
                '        chi^2', chiSquared(1), chiSquared(2)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1'};
        columnformat = {'char', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.592 0.504 0.3 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 3
        % Data for table
        dat =  {'        a1', a1(1), a1(2), a1(3);...
                '        a2', a2(1), a2(2), a2(3);...   
                '        beta', beta(1), beta(2), beta(3);...
                '        tau', tau(1), tau(2), tau(3); ...
                '        numFuncs', numFuncs(1), numFuncs(2), numFuncs(3); ...
                '        chi^2', chiSquared(1), chiSquared(2), chiSquared(3)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1', 'Decay 2'};
        columnformat = {'char', 'numeric', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.496 0.504 0.384 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 4
        % Data for table
        dat =  {'        a1', a1(1), a1(2), a1(3), a1(4);...
                '        a2', a2(1), a2(2), a2(3), a2(4);...   
                '        beta', beta(1), beta(2), beta(3), beta(4);...
                '        tau', tau(1), tau(2), tau(3), tau(4); ...
                '        numFuncs', numFuncs(1), numFuncs(2), numFuncs(3), numFuncs(4); ...
                '        chi^2', chiSquared(1), chiSquared(2), chiSquared(3), chiSquared(4)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1', 'Decay 2', 'Increase 2'};
        columnformat = {'char', 'numeric', 'numeric', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.4 0.504 0.48 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    else
        error('plotStrExpFit() is not formatted to fit this function.');
    end
else
        %--------------------------------------------------------------------------
    % Add data to table  and format based on how many stretched 
    % exponential chunks you have
    if numStrExpChunks == 1
        % Data for table
        dat =  {'        a1', a1(1);...
                '        a2', a2(1);...   
                '        beta', beta(1);...
                '        tau', tau(1); ...
                '        chi^2', chiSquared(1)};
        columnname =   {'Parameter', 'Decay 1'};
        columnformat = {'char', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.688 0.504 0.192 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 2
        % Data for table
        dat =  {'        a1', a1(1), a1(2);...
                '        a2', a2(1), a2(2);...   
                '        beta', beta(1), beta(2);...
                '        tau', tau(1), tau(2); ...
                '        chi^2', chiSquared(1), chiSquared(2)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1'};
        columnformat = {'char', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.592 0.504 0.3 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 3
        % Data for table
        dat =  {'        a1', a1(1), a1(2), a1(3);...
                '        a2', a2(1), a2(2), a2(3);...   
                '        beta', beta(1), beta(2), beta(3);...
                '        tau', tau(1), tau(2), tau(3); ...
                '        chi^2', chiSquared(1), chiSquared(2), chiSquared(3)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1', 'Decay 2'};
        columnformat = {'char', 'numeric', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.496 0.504 0.384 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    elseif numStrExpChunks == 4
        % Data for table
        dat =  {'        a1', a1(1), a1(2), a1(3), a1(4);...
                '        a2', a2(1), a2(2), a2(3), a2(4);...   
                '        beta', beta(1), beta(2), beta(3), beta(4);...
                '        tau', tau(1), tau(2), tau(3), tau(4); ...
                '        chi^2', chiSquared(1), chiSquared(2), chiSquared(3), chiSquared(4)};
        columnname =   {'Parameter', 'Decay 1', 'Increase 1', 'Decay 2', 'Increase 2'};
        columnformat = {'char', 'numeric', 'numeric', 'numeric', 'numeric'}; 
        t = uitable('Units','normalized', 'Position',...
                    [0.4 0.504 0.48 0.276],'Data', dat,... 
                    'ColumnName', columnname,...
                    'ColumnFormat', columnformat,...
                    'RowName',[]); 
    else
        error('plotStrExpFit() is not formatted to fit this function.');
    end
end
end

