function [fitresult, gof] = strExpFit(x, y, start)
%==========================================================================
%  Create a fit.
%
%  Data for Stretched Exponential fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%

%  Auto-generated by MATLAB on 18-Feb-2017 15:17:45
%==========================================================================
% I'm not entirely sure what all of this stuff does.
%                   - Laura Nichols
%==========================================================================

[xData, yData] = prepareCurveData( x, y );
% Set up fittype and options.
ft = fittype( sprintf('a1-(a1-%d)*exp(-(t/tau)^beta)', yData(1)), 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [yData(1)/2 0 0];
opts.StartPoint = start;
opts.Upper = [Inf 1 xData(end)/2];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );




